### ISSUE TITLE
Sizing doesn't do anything

### ISSUE THREAD

**Issue by megamidge** [robcresswell/vue-material-design-icons#27]
Applying :size="48" makes no difference, as does

```css
.material-design-icon.icon-2x {
  height: 2em;
  width: 2em;
}
 
.material-design-icon.icon-2x > .material-design-icon__svg {
  height: 2em;
  width: 2em;
}
```

Using dev tools shows this class settings the size to 1rem:

```css
.material-design-icon > .material-design-icon__svg {
  height: 1em;
  width: 1em;
  fill: currentColor;
  position: absolute;
  bottom: -0.125em;
}
```

What gives?
