### ISSUE TITLE
Property :size is not working correctly

### ISSUE THREAD

**Issue by kaczor6418** [robcresswell/vue-material-design-icons#93]
Property **:size** is not working because of width and height of ```.material-desig-cion > material-design-icon__svg```.

**Comment by kaczor6418** [comment]
I created [PR: fix(size): size property #94](https://github.com/robcresswell/vue-material-design-icons/pull/94) which will fix this bug

**Comment by robcresswell** [comment]
Hi @kaczor6418, thanks for raising an issue! This isn't a bug, I think. I recommend using the CSS *OR* the JS for styling, but not both. The CSS is optional, so you can write your own if you don't want to use the default; its only a few lines. Your fix will remove a lot of the default sizing from the CSS, which I disagree with.

See the note in https://github.com/robcresswell/vue-material-design-icons#props under `fillColor` about using one or the other. I'll update it for clarity

**Comment by kaczor6418** [comment]
@robcresswell But in documentation I can read that I can use property :size to set size of icon but currently it is not possible
> ```size - This property overrides the `width` and `height` attributes on the
  SVG. The default is `24`. Example:
 <android-icon :size="48" />```

 to set size of icon but currently it is not possible. For example: 
```js
    <header>
      <menu-icon :size="100" />
      <search-web-icon :size="100" />
    </header>
```
so size of this ican should be 100 x 100, but it is not. Size of icon is still 24 x 24 which is default size of this icon. So in my opinion it is a bug

**Comment by kaczor6418** [comment]
@robcresswell you do not have to use this css it is just my proposition. And i can say that you can do it even easier, you can remove whole ```.material-design-icon > .material-design-icon__svg``` class and center all icns in ```.material-design-icon``` class. Example below: 
```css
.material-design-icon {
  display: flex;
  align-items: center;
  justify-content: center;
}
```
I do not see any benefits of this :
```css
.material-design-icon {
  display: inline-flex;
  align-self: center;
  position: relative;
  height: 1em;
  width: 1em;
}
.material-design-icon > .material-design-icon__svg {
  height: 1em;
  width: 1em;
  fill: currentColor;
  position: absolute;
  bottom: -0.125em;
}
```
If there is any please tell me. I am curious
